#:schema ./.aviutl2-cli/aviutl2.schema.json
[project]
id = "script_jp_patch"
name = "スクリプト日本語化パッチ"
version = "YYYY.MM.DD"

# --- original ---
[artifacts.original]
source = "スクリプト日本語化パッチ.aul2"
destination = "Language/スクリプト日本語化パッチ.aul2"

[artifacts.original.profiles.release]
enabled = true

[release]
output_dir = "release"
package_template = "package.txt"
package_information = "{name} {version} by Garech"
zip_name="{id}"