name: Release Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g. 2026.03.21)"
        required: true

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: "recursive"

      - name: Set up cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall

      - name: Set up mise
        uses: jdx/mise-action@v3
        with:
          install: true
          experimental: true

      - name: Prepare artifacts
        shell: bash
        run: |
          au2 release --set-version "${{ github.event.inputs.version }}"

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          gh release create "${{ github.event.inputs.version }}" \
            --title "スクリプト日本語化パッチ ${{ github.event.inputs.version }}" \
            --draft \
            --notes "---
            \`スクリプト日本語化パッチ.au2pkg.zip\`をダウンロードし、ZIPファイルをAviUtl2のプレビューにドラッグ&ドロップしてください。

          ※必ず[最新バージョンのAviUtl2](https://spring-fragrance.mints.ne.jp/aviutl/)を導入してください。 ※beta50以降が推奨環境です。"

          gh release upload "${{ github.event.inputs.version }}" \
            "release/script_jp_patch.au2pkg.zip#スクリプト日本語化パッチ.au2pkg.zip" \
            --clobber